### ISSUE TITLE
Heel nice die uitgebreide comments

### ISSUE THREAD

**Issue by kriskuiper** [iSirThijs/web-app-from-scratch-1920#10]
Ik hou er persoonlijk ook van om die [comments zo met `@param`](https://github.com/iSirThijs/web-app-from-scratch-1920/blob/development/scripts/modules/fetch-utilities.mjs#L6-L10) etc. te schrijven zodat je code editor dat later oppikt. Heel nice!

**Comment by iamDistractech** [comment]
Thanks!!! 😊
