### ISSUE TITLE
Misschien linkje naar de documentatie van URL erboven gooien

### ISSUE THREAD

**Issue by kriskuiper** [iSirThijs/web-app-from-scratch-1920#11]
Ik wist niet wat er gebeurde omdat ik niet bekend ben met met de URL constructor binnen JS. Misschien een linkje erboven neerzetten naar de docs van hoe het werkt etc.

**Comment by iamDistractech** [comment]
Yup kan ik inderdaad iets verduidelijken met een link naar MDN bijvoorbeeld

**Comment by iamDistractech** [comment]
Added a link in the code 👍
