### ISSUE TITLE
Catch kan korter

### ISSUE THREAD

**Issue by kriskuiper** [iSirThijs/web-app-from-scratch-1920#12]
[Dit kan korter](https://github.com/iSirThijs/web-app-from-scratch-1920/blob/development/scripts/main.mjs#L25)

Je zou gewoon het volgende kunnen doen:

```js
fetch()
  .then(handleSuccess)
  .catch(console.error)
```

**Comment by iamDistractech** [comment]
True, maar hier komt nog een dedicated error handle function later

**Comment by iamDistractech** [comment]
Issue toegevoegd om een dedicated error functie te schrijven #13
