### ISSUE TITLE
The structure of your code is quite professional but the functionality is lacking

### ISSUE THREAD

**Issue by Razpudding** [iSirThijs/web-app-from-scratch-1920#16]
You've set up the code in a professional way. Is that what you wanted to learn during this course? Might be a good idea to discuss extra challenges with a teacher.
Be careful not to lose the forest for the trees ;)

**Comment by iamDistractech** [comment]
This course I'm trying to focus on doing all the assignment stuff first and afterwards doing the extra challenges. I am experimenting with different ways of managing this for myself. 1 of those is using GitHub tools. I currently am also experimenting with Virtual Dom and diffing, but only when time is left.
