### ISSUE TITLE
README API

### ISSUE THREAD

**Issue by WesselSmit** [iSirThijs/web-app-from-scratch-1920#26]
The README "data sources" is incomplete, consider adding the following items to your README:
- rate limit
- available parameters
- authorisation
- pricing (free? or fremium?)
- a brief description of what the API does and what kind of data to expect (NOTE: this is NOT the data object screenshot)

**Comment by iamDistractech** [comment]
I'm planning on doing this more in-depth in my wiki and then make a nice summary on the readme
(see issue #3).
