### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by WesselSmit** [iSirThijs/web-app-from-scratch-1920#30]
https://github.com/iSirThijs/web-app-from-scratch-1920/blob/0ead175aefc4574c8c593300d047da052c47a1ca/src/utilities/fetcher.mjs#L12-L17

In the code snippet above you use two different type of if/else statements. I recommend keeping a consistent coding style

**Comment by iamDistractech** [comment]
I personally think this style is more readable, since the `if` is a one-liner. (I think this is what you mean?)
