### ISSUE TITLE
Separate functionality maybe?

### ISSUE THREAD

**Issue by devsjors** [iSirThijs/web-app-from-scratch-1920#5]
This function is called createSearch. Here you create a form which looks for games in the fetched data.
https://github.com/iSirThijs/web-app-from-scratch-1920/blob/development/scripts/main.mjs#L7-L18

You also add a EventListener which searches for the games and console.logs the results. Maybe more clear to do this in two separate functions? 
https://github.com/iSirThijs/web-app-from-scratch-1920/blob/development/scripts/main.mjs#L20-L26

**Comment by iamDistractech** [comment]
Will do, this was code was just a way to get a search bar. This issue: #1 will resolve this
