### ISSUE TITLE
Const in plaats van let gebruiken

### ISSUE THREAD

**Issue by kriskuiper** [iSirThijs/web-app-from-scratch-1920#9]
In [dit stukje code](https://github.com/iSirThijs/web-app-from-scratch-1920/blob/development/scripts/main.mjs#L22) gebruik je een `let`, maar voor zover ik kan zien re-assign je later niks dus kan gewoon een `const` zijn

**Comment by iamDistractech** [comment]
Kan inderdaad iets consistenter `const` en `let` gebruiken 😅
